/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAbout: typeof import('./components/AppAbout.vue')['default']
    AppMessages: typeof import('./components/AppMessages.vue')['default']
    AppNav: typeof import('./components/AppNav.vue')['default']
    AppNotifier: typeof import('./components/AppNotifier.vue')['default']
    AppPortfolio: typeof import('./components/AppPortfolio.vue')['default']
    Auth: typeof import('./components/Auth.vue')['default']
    Chart: typeof import('./components/Chart.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillModal: typeof import('./components/SkillModal.vue')['default']
    Social: typeof import('./components/Social.vue')['default']
  }
}
